name: uts_todo
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.0 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter: 
    sdk: flutter
  table_calendar: ^3.0.9
  get_storage: ^2.1.1
  intl: ^0.18.1

dev_dependencies: 
  flutter_lints: 3.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  fonts:
    - family: HindSiliguriBold
      fonts:
        - asset: assets/fonts/HindSiliguri-Bold.ttf
    - family: HindSiliguriLight
      fonts:
        - asset: assets/fonts/HindSiliguri-Light.ttf
    - family: HindSiliguriMedium
      fonts:
        - asset: assets/fonts/HindSiliguri-Medium.ttf
    - family: HindSiliguriRegular
      fonts:
        - asset: assets/fonts/HindSiliguri-Regular.ttf
    - family: HindSiliguriSemiBold
      fonts:
        - asset: assets/fonts/HindSiliguri-SemiBold.ttf

